/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DeliveryAddress {
  'floor' : string,
  'area' : string,
  'flat' : string,
  'name' : string,
  'addressType' : string,
  'landmark' : string,
  'phone' : bigint,
}
export interface Order {
  'status' : OrderStatus,
  'deliveryCharge' : bigint,
  'paymentMethod' : PaymentMethod,
  'orderId' : bigint,
  'totalAmount' : bigint,
  'address' : DeliveryAddress,
  'timestamp' : bigint,
  'products' : Array<ProductOrder>,
}
export type OrderStatus = { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export type PaymentMethod = { 'cod' : null } |
  { 'upi' : string };
export type Price = bigint;
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'rating' : Rating,
  'price' : Price,
}
export interface ProductOrder {
  'name' : string,
  'size' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export type Rating = bigint;
export interface _SERVICE {
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getOrderById' : ActorMethod<[bigint], [] | [Order]>,
  'getProductById' : ActorMethod<[bigint], Product>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'submitOrder' : ActorMethod<[Order], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];