/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'cod' : IDL.Null,
  'upi' : IDL.Text,
});
export const DeliveryAddress = IDL.Record({
  'floor' : IDL.Text,
  'area' : IDL.Text,
  'flat' : IDL.Text,
  'name' : IDL.Text,
  'addressType' : IDL.Text,
  'landmark' : IDL.Text,
  'phone' : IDL.Nat,
});
export const ProductOrder = IDL.Record({
  'name' : IDL.Text,
  'size' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'status' : OrderStatus,
  'deliveryCharge' : IDL.Nat,
  'paymentMethod' : PaymentMethod,
  'orderId' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'address' : DeliveryAddress,
  'timestamp' : IDL.Int,
  'products' : IDL.Vec(ProductOrder),
});
export const Rating = IDL.Nat;
export const Price = IDL.Nat;
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'rating' : Rating,
  'price' : Price,
});
export const UserProfile = IDL.Record({
  'floor' : IDL.Text,
  'area' : IDL.Text,
  'flat' : IDL.Text,
  'name' : IDL.Text,
  'addressType' : IDL.Text,
  'landmark' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getUserByPhone' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'saveUserProfile' : IDL.Func([UserProfile], [], []),
  'submitOrder' : IDL.Func([Order], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({ 'cod' : IDL.Null, 'upi' : IDL.Text });
  const DeliveryAddress = IDL.Record({
    'floor' : IDL.Text,
    'area' : IDL.Text,
    'flat' : IDL.Text,
    'name' : IDL.Text,
    'addressType' : IDL.Text,
    'landmark' : IDL.Text,
    'phone' : IDL.Nat,
  });
  const ProductOrder = IDL.Record({
    'name' : IDL.Text,
    'size' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'status' : OrderStatus,
    'deliveryCharge' : IDL.Nat,
    'paymentMethod' : PaymentMethod,
    'orderId' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'address' : DeliveryAddress,
    'timestamp' : IDL.Int,
    'products' : IDL.Vec(ProductOrder),
  });
  const Rating = IDL.Nat;
  const Price = IDL.Nat;
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'rating' : Rating,
    'price' : Price,
  });
  const UserProfile = IDL.Record({
    'floor' : IDL.Text,
    'area' : IDL.Text,
    'flat' : IDL.Text,
    'name' : IDL.Text,
    'addressType' : IDL.Text,
    'landmark' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserByPhone' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'saveUserProfile' : IDL.Func([UserProfile], [], []),
    'submitOrder' : IDL.Func([Order], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };